spring.application.name=task_list

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/task_list
spring.datasource.username=admin
spring.datasource.password=admin

# JPA/Hibernate Configuration - Desabilitar criação automática (Flyway gerencia)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

security.token.secret.admin=TASK_LIST_@JAVA#ADMIN
security.token.secret.user=TASK_LIST_@JAVA#USER
